FROM python:3.13-slim

WORKDIR /app

COPY pyproject.toml .
COPY README.md .
COPY backend/ ./backend/

RUN pip install --no-cache-dir -e .
COPY scripts/ ./scripts/
COPY webpages/ ./webpages/

ENV PYTHONUNBUFFERED=1

CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
